#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 18 16:03:42 2023

@author: ethanmikel
"""
#Author: Ethan Mikel
#Homework Number & Name: 1 & Face Mask Store Sales
#Due Date: Jan. 25 by 12pm
#Program Description: This program is designed for a user to input a product's name, price, cost, and the quantity of the product sold. To then calculate the total revenue generated, total profit, and the precentage of profit generated by the product. 

#Asks the user to input various different variables like the name of the product (str), the price of the product (float), the cost of the product (float), and the quantity of the product sold (int).
product_name=input("What is the name of the product? ")
product_price=float(input("Price of the Product: $"))
product_cost=float(input("Cost of the Product: $"))
quantity_sold=int(input("Quantity of Product Sold: "))

total_rev=product_price*quantity_sold #Calculates the total revenue of a product sold by multiplying the price of the product by the quantity sold. 
total_cost=product_cost*quantity_sold #Calculates the total cost of the product by multiplying the product's cost by the quantity sold. 
total_profit=total_rev-total_cost #Calculates the total profit gained by subtracting the total revenue (previously calculated) from the total cost (previously calculated)
profit_precentage=round(total_profit/total_rev*100) #Calculates the profit precentage by total profit (previosuly calculated) over total revenue (previously calculated), then multipling by 100 and rounding it to a whole number by using round() without any number on the end.

#Prints out the name of the product, the revenue generated, the total cost of the product, quantity of the product sold, total profit, rounds the variables to the respective  and the profit precentage. It formats every variable by adding in decimals, commas, and converts both int and floats into str. 
print()
print("Name of Product:", product_name)
print("Total Revenue Generated: $"+str(format(total_rev, ',.2f')))
print("Total Cost of the Product: $"+str(format(total_cost, ',.2f')))
print("Total Quantity of Product Sold: "+str(format(quantity_sold, ','))+" unit(s)")
print("Total Profit: $"+str(format(total_profit, ',.2f')))
print("Precentage of Profit Generated by the Product: "+str(profit_precentage)+"%")